spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instituto
    username: postgres
    password: emilio
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # Es útil tenerlo en true en local para ver las consultas
    properties:
      hibernate:
        format_sql: true
    open-in-view: false