spring:
  datasource:
    url: jdbc:postgresql://dpg-d80pa8v7f7vs73d3o6o0-a.frankfurt-postgres.render.com/instituto_wwnw
    username: instituto_wwnw_user
    password: CCY21x6CLdlK0YTKCArlKQOOQ8DKYRnM
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # En producción es mejor false para no saturar los logs
    properties:
      hibernate:
        format_sql: false
    open-in-view: false